### ISSUE TITLE
下载服务器失败

### ISSUE THREAD

**Issue by Pulaimarii** [xulihang/ImageTrans_chrome_extension#5]
点击“启动服务器”按钮后，提示服务器未下载，点击下载后，进度一直显示0/0，几秒后显示下载失败。
已经尝试过挂全局梯子/完全不挂梯，结果相同

**Comment by xulihang** [comment]
可以手动下载：https://github.com/xulihang/ImageTrans_wsServer/releases/download/builds/ImageTrans_wsServer.jar

然后放到软件目录下

**Comment by Pulaimarii** [comment]
您好，已成功安装服务器并且启动+勾选重新连接，
但点击扩展程序里的translate一直提示 Failed to connect to ImageTrans server

**Comment by xulihang** [comment]
看下能不能打开<https://local.basiccat.org:51043/>。

然后浏览器里按F12打开开发者工具，看一下console里有什么错误输出

**Comment by Pulaimarii** [comment]
您好，显示的是：

favicon.ico:1     Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load source map: Could not load content for chrome-extension://cofdbpoegempjloogbagkncekinflcnj/build/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

**Comment by xulihang** [comment]
这个应该不是插件的错误。执行翻译操作时的日志呢

**Comment by Pulaimarii** [comment]
ImageTrans提示的错误是：
error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
]
	at org.opencv.imgproc.Imgproc.cvtColor_1(Native Method)
	at org.opencv.imgproc.Imgproc.cvtColor(Imgproc.java:7057)
	at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at anywheresoftware.b4j.object.JavaObject.RunMethodJO(JavaObject.java:139)
	at org.xulihang.imagetrans.cv2._cvtcolor(cv2.java:201)
	at org.xulihang.imagetrans.textlocalization._threshold(textlocalization.java:1646)
	at org.xulihang.imagetrans.textlocalization._connectedcomponents(textlocalization.java:137)
	at org.xulihang.imagetrans.textlocalization._getstats(textlocalization.java:796)
	at org.xulihang.imagetrans.textlocalization._gettextstats(textlocalization.java:1066)
	at org.xulihang.imagetrans.textlocalization$ResumableSub_getTextAreas.resume(textlocalization.java:880)
	at org.xulihang.imagetrans.textlocalization._gettextareas(textlocalization.java:804)
	at org.xulihang.imagetrans.main$ResumableSub_LocalizeTextHeuristically.resume(main.java:12252)
	at org.xulihang.imagetrans.main._localizetextheuristically(main.java:12137)
	at org.xulihang.imagetrans.main$ResumableSub_BatchTranslation.resume(main.java:3099)
	at org.xulihang.imagetrans.main._batchtranslation(main.java:2743)
	at org.xulihang.imagetrans.server$ResumableSub_wsh_Translate.resume(server.java:1015)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)


然后直接用extension里面的Translate，console里面显示的是
from the extension
getImage.js:14 translate
getImage.js:24 https://s.pximg.net/www/js/build/14e52f8ff79c3dc931eb16c6f4b53890.svg
getImage.js:67 {src: 'https://s.pximg.net/www/js/build/14e52f8ff79c3dc931eb16c6f4b53890.svg'}
jquery-3.5.1.min.js:2     POST https://local.basiccat.org:51043/translate net::ERR_CONNECTION_CLOSED

但是把图片下载下来上传到您给的网址是可以翻译的（必须关闭梯子）

是因为我翻译的图片是推特和Pixiv里面的吗？使用插件的时候一直开着全局梯子

**Comment by xulihang** [comment]
这里翻译错图片了，需要鼠标悬浮在要翻译的图片上，然后用CTRL+SHIFT+F快捷键调出窗口进行翻译。

**Comment by Pulaimarii** [comment]
经您提醒，以下所描述的全部操作与报错均在鼠标悬停图片→CtrlShiftF→Tab→Enter 调用快捷键前提下

我对比测试了一下可能是网的问题……因为我翻墙的频率比较高，外加大部分国内网站开着梯子也是可以正常上的，我就总是挂着全局梯子。

我挂着梯点开您给的网址（https://local.basiccat.org:51043/translator）显示的是“无法访问此网站”，
但是关闭梯子后可正常打开，将推特的图片下载好并上传至该网站也可正常翻译。

于是我尝试将pixiv的图片加载出来后关掉梯子，看看能不能使用ImageTrans，结果显示的是 Bad result. Is ImageTrans running correctly?
我又重新挂上梯子，显示的还是 Failed to connect to ImageTrans server.

然后您视频教程中使用的是腾讯漫画，我将梯子关闭，按照正常操作随机点开一章腾讯漫画，识别与翻译都是成功的。
感觉可能是我的梯子有问题，或者basicCAT与梯子冲突的问题（例如淘宝就屏蔽了所有梯子）？

**Comment by xulihang** [comment]
ImageTrans会直接用链接重新下载一次图片，如果不能下载的话就会报错的

**Comment by xulihang** [comment]
pixiv的图现在已经可以翻了。需要再装一个[Allow CORS](https://chromewebstore.google.com/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf)的插件，允许获取图片数据。
