### ISSUE TITLE
how to connect ImageTrans with brower?

### ISSUE THREAD

**Issue by apt42541** [xulihang/ImageTrans_chrome_extension#8]
1. ![image](https://github.com/user-attachments/assets/1f49100b-d26d-4fb5-bed8-0eda34f687f0)
2. 
![image](https://github.com/user-attachments/assets/6423e9f0-6913-460f-b50d-8330d4e9563c)
3. 
![image](https://github.com/user-attachments/assets/84e8027e-4d87-486f-b7eb-e72b869dc539)
4. 
![image](https://github.com/user-attachments/assets/184923d7-ec9f-4eb3-9a42-8ac2da06ffcc)

how should i do?

**Comment by xulihang** [comment]
Go to https://local.basiccat.org:51043/translator to see if you can translate an image.

**Comment by apt42541** [comment]
not work, and this from console log at ac.qq 
![image](https://github.com/user-attachments/assets/970cb8af-6fb9-4714-89ec-d86b12c0b7ad)

**Comment by xulihang** [comment]
You are using an old version of ImageTrans. Update it to 3.13.1 or use the old wsServer: https://github.com/xulihang/ImageTrans_wsServer/releases/download/builds/ImageTrans_wsServer_2024.jar

Rename it as ImageTrans_wsServer.jar in ImageTrans's folder.

**Comment by apt42541** [comment]
ok , it work now thanks

**Comment by apt42541** [comment]
error: java.lang.NullPointerException: Cannot invoke "anywheresoftware.b4a.BA$IterableList.getSize()" because "<local13>" is null
StackTrace: java.lang.NullPointerException: Cannot invoke "anywheresoftware.b4a.BA$IterableList.getSize()" because "<local13>" is null
	at org.xulihang.imagetrans.silenttranslator._showdetection(silenttranslator.java:2883)
	at org.xulihang.imagetrans.silenttranslator$ResumableSub_TranslateOne.resume(silenttranslator.java:3369)
	at org.xulihang.imagetrans.silenttranslator._translateone(silenttranslator.java:3060)
	at org.xulihang.imagetrans.silenttranslator$ResumableSub_TranslateOneGUI.resume(silenttranslator.java:3575)
	at org.xulihang.imagetrans.silenttranslator._translateonegui(silenttranslator.java:3525)
	at org.xulihang.imagetrans.server$ResumableSub_wsh_Translate.resume(server.java:1009)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@23-ea/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@23-ea/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@23-ea/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by xulihang** [comment]
Some step is wrong.

Silent Translator used with the Chrome Extension has been removed from the latest version so I am not giving support any more.
